USE [master]
GO

/****** Object:  Database [Game]    Script Date: 18.09.2020 0:19:50 ******/
CREATE DATABASE [Game]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BlogUser', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BlogUser.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BlogUser_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BlogUser_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Game].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Game] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Game] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Game] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Game] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Game] SET ARITHABORT OFF 
GO

ALTER DATABASE [Game] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Game] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Game] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Game] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Game] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Game] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Game] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Game] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Game] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Game] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Game] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Game] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Game] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Game] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Game] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Game] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Game] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Game] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Game] SET  MULTI_USER 
GO

ALTER DATABASE [Game] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Game] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Game] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Game] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Game] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Game] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Game] SET  READ_WRITE 
GO

